# Generated by Django 3.2.5 on 2021-09-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_auto_20210925_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('I', 'Intermediário'), ('B', 'Básico'), ('A', 'Avançado')], default='B', max_length=1),
        ),
    ]
